### ISSUE TITLE
Recommended N is systematically higher for networks with negative edges.

### ISSUE THREAD

**Issue by axrhart** [mihaiconstantin/powerly#34]
Dear Mihai,

we want to use your package to support our sample size considerations in an upcoming proposal. While playing around with different options for the possible network, we noticed that matrices with an increasing number of negative edges tend to produce a remarkably higher sample size recommendation than positive networks. For example, flipping the sign of all edges on an all positive matrix results in an increase in recommended sample size by +162.

Code to reproduce:
```
# Params
seed <- 2022
nodes <- 10
density <- 0.4
positive <- 0.9
min_N <- 50
max_N <- 1000

# Set seed
set.seed(seed)

# Generate model
model_matrix <- powerly::generate_model("ggm",
                                        nodes = nodes,
                                        density = density,
                                        positive = positive)

# Flip signs
model_matrix_neg <- model_matrix * -1

# Compute results
results <- powerly::powerly(min_N,
                            max_N,
                            model_matrix = model_matrix)

# Method run completed (18.6493 sec):
# - converged: yes
# - iterations: 1
# - recommendation: 302

results_neg <- powerly::powerly(min_N,
                            max_N,
                            model_matrix = model_matrix_neg)

# Method run completed (35.4334 sec):
# - converged: yes
# - iterations: 2
# - recommendation: 464
```

I think I am using the CRAN version of powerly.

Unfortunately, I have not much experience with network theory and I had some difficulties wrapping my head around your code without some class diagrams to guide my exploration. Is this the expected behavior that matrices with negative edges require more participants to reach the same sensitivity? Or am I doing something wrong?

Best,
Alex

P.S: Thanks for your effort developing this package. So far, the workflow and plots have been really enjoyable/helpful and it was super interesting reading some object-oriented R code. 😊

**Comment by mihaiconstantin** [comment]
@axrhart, I will mark this as completed. If you have further questions on the topic, please feel free to reopen or reach out!
